Repository Ahmad-Elmahallawy/iCondo, pull requests merged in 2024-04, with the labels that each got.

#418 417 task 036 01 update the reservation schema
  server/package-lock.json
  server/prisma/migrations/20240410172027_update_reservation/migration.sql
  server/prisma/migrations/20240410172543_fix_name_in_reservation/migration.sql
  server/prisma/schema.prisma
  server/schema.graphql
  server/src/commonFacility/base/CommonFacility.ts
  server/src/commonFacility/base/CommonFacilityCreateInput.ts
  server/src/commonFacility/base/CommonFacilityOrderByInput.ts
  server/src/commonFacility/base/CommonFacilityUpdateInput.ts
  server/src/commonFacility/base/CommonFacilityWhereInput.ts
  server/src/commonFacility/base/commonFacility.controller.base.spec.ts
  server/src/commonFacility/base/commonFacility.controller.base.ts
  server/src/commonFacility/base/commonFacility.resolver.base.ts
  server/src/commonFacility/base/commonFacility.service.base.ts
  server/src/post/base/post.service.base.ts
  server/src/property/base/CommonFacilityCreateNestedManyWithoutPropertiesInput.ts
  server/src/property/base/CommonFacilityUpdateManyWithoutPropertiesInput.ts
  server/src/property/base/Property.ts
  server/src/property/base/PropertyCreateInput.ts
  server/src/property/base/PropertyUpdateInput.ts
  server/src/property/base/PropertyWhereInput.ts
  server/src/property/base/property.controller.base.ts
  server/src/property/base/property.resolver.base.ts
  server/src/property/base/property.service.base.ts
  server/src/reservation/base/Reservation.ts
  server/src/reservation/base/ReservationCreateInput.ts
  server/src/reservation/base/ReservationOrderByInput.ts
  server/src/reservation/base/ReservationUpdateInput.ts
  server/src/reservation/base/ReservationWhereInput.ts
  server/src/reservation/base/reservation.controller.base.ts
  server/src/reservation/base/reservation.resolver.base.ts
  server/src/reservation/base/reservation.service.base.ts
  server/src/user/base/user.controller.base.ts
Labels: documentation, enhancement, Backend

#424 At log in, return property id of user's first condo unit
  server/package-lock.json
  server/schema.graphql
  server/src/auth/UserInfo.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/financialSystem/financialSystem.controller.ts
  server/src/grants.json
Labels: enhancement, Backend

#434 426 task 034 03 add boolean to condounit schema so we know when its been paid
  server/prisma/migrations/20240412191000_add_is_paid_attribute/migration.sql
  server/prisma/schema.prisma
  server/src/condoUnit/base/CondoUnit.ts
  server/src/condoUnit/base/CondoUnitCreateInput.ts
  server/src/condoUnit/base/CondoUnitOrderByInput.ts
  server/src/condoUnit/base/CondoUnitUpdateInput.ts
  server/src/condoUnit/base/CondoUnitWhereInput.ts
  server/src/condoUnit/base/condoUnit.controller.base.spec.ts
  server/src/condoUnit/base/condoUnit.controller.base.ts
  server/src/property/base/property.controller.base.ts
Labels: Task, Backend

#436 Common facilities status page for Company
  frontend/src/App.tsx
  frontend/src/Components/CommonFacilities/IndividualFacility.tsx
  frontend/src/Pages/FacilitiesStatusPage.tsx
  frontend/src/Style/CommonFacilitiesStyle/IndividualFacility.css
  frontend/src/api.ts
  frontend/src/urls.ts
Labels: Task

#439 Pay condo fee btn and API integration
  frontend/src/Components/CondoProfile/IndividualCondoProfile.test.tsx
  frontend/src/Components/CondoProfile/IndividualCondoProfile.tsx
  frontend/src/Style/CondoProfileStyle/IndividualCondoProfileStyle.css
  frontend/src/api.ts
Labels: Task

#441 Fixed failing auth service tests
  server/src/auth/auth.service.spec.ts
Labels: bug, Backend

#451 Corrected icon name capitalization
  frontend/src/Pages/CondoOwnerDashboardLandingPage.tsx
  frontend/src/Pages/RentalUserDashboard.tsx
Labels: bug, Frontend

#415 414 task 031 integrate api for the mobile app
  condo-management-app/App.js
  condo-management-app/Component/Button/styles.js
  condo-management-app/Component/CondoDetails/index.js
  condo-management-app/Component/ProductHomeItem/index.js
  condo-management-app/Component/ProductHomeItem/styles.js
  condo-management-app/Routes.js
  condo-management-app/app.json
  condo-management-app/package-lock.json
  condo-management-app/package.json
  condo-management-app/screens/app/CreateListing/index.js
  condo-management-app/screens/app/Favorites/index.js
  condo-management-app/screens/app/Home/index.js
  condo-management-app/screens/app/MyListings/index.js
  condo-management-app/screens/app/Profile/index.js
  condo-management-app/screens/app/Settings/index.js
  condo-management-app/screens/auth/SignIn/index.js
  condo-management-app/screens/auth/SignUpAsAdmin/index.js
  condo-management-app/screens/auth/SignUpAsClient/index.js
  condo-management-app/utils/backendRequest.js
  condo-management-app/utils/request.js
  condo-management-app/yarn.lock
Labels: Task, Backend, App

#461 BUG-12 & BUG-13 - Fixed Displaying the Correct Properties for Common Facilities
  frontend/src/Components/Reservations/Calendar.tsx
  frontend/src/Components/Reservations/CommonFacility.tsx
  frontend/src/Pages/FacilitiesStatusPage.tsx
  frontend/src/Style/CommonFacilitiesStyle/IndividualFacility.css
  frontend/src/api.ts
  frontend/src/urls.ts
Labels: bug

#463 fixed first come first serve reservation
  frontend/src/Components/Reservations/Calendar.tsx
  frontend/src/Components/Reservations/ReservationModal.tsx
Labels: enhancement, Frontend

#465 464 bug 14 notifications not showing
  frontend/src/Pages/NotificationPageManager.tsx
Labels: bug

#468 467 bug 16 wrong spelling in company dashboard
  frontend/src/Pages/CompanyDashboardLandingPage.tsx
Labels: bug, Frontend
